package com.rnpp.greendao_example.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rnpp.greendao_example.db.ms_user;
import com.rnpp.greendao_example.db.ms_userInfo;
import com.rnpp.greendao_example.db.ms_userLoginHistory;

import com.rnpp.greendao_example.db.ms_userDao;
import com.rnpp.greendao_example.db.ms_userInfoDao;
import com.rnpp.greendao_example.db.ms_userLoginHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ms_userDaoConfig;
    private final DaoConfig ms_userInfoDaoConfig;
    private final DaoConfig ms_userLoginHistoryDaoConfig;

    private final ms_userDao ms_userDao;
    private final ms_userInfoDao ms_userInfoDao;
    private final ms_userLoginHistoryDao ms_userLoginHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ms_userDaoConfig = daoConfigMap.get(ms_userDao.class).clone();
        ms_userDaoConfig.initIdentityScope(type);

        ms_userInfoDaoConfig = daoConfigMap.get(ms_userInfoDao.class).clone();
        ms_userInfoDaoConfig.initIdentityScope(type);

        ms_userLoginHistoryDaoConfig = daoConfigMap.get(ms_userLoginHistoryDao.class).clone();
        ms_userLoginHistoryDaoConfig.initIdentityScope(type);

        ms_userDao = new ms_userDao(ms_userDaoConfig, this);
        ms_userInfoDao = new ms_userInfoDao(ms_userInfoDaoConfig, this);
        ms_userLoginHistoryDao = new ms_userLoginHistoryDao(ms_userLoginHistoryDaoConfig, this);

        registerDao(ms_user.class, ms_userDao);
        registerDao(ms_userInfo.class, ms_userInfoDao);
        registerDao(ms_userLoginHistory.class, ms_userLoginHistoryDao);
    }
    
    public void clear() {
        ms_userDaoConfig.clearIdentityScope();
        ms_userInfoDaoConfig.clearIdentityScope();
        ms_userLoginHistoryDaoConfig.clearIdentityScope();
    }

    public ms_userDao getMs_userDao() {
        return ms_userDao;
    }

    public ms_userInfoDao getMs_userInfoDao() {
        return ms_userInfoDao;
    }

    public ms_userLoginHistoryDao getMs_userLoginHistoryDao() {
        return ms_userLoginHistoryDao;
    }

}
