package com.rnpp.greendao_example.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MS_USER_LOGIN_HISTORY".
 */
@Entity
public class ms_userLoginHistory {

    @NotNull
    private String data_sync_status;

    @NotNull
    private String data_sync_date;

    @NotNull
    private String update_at;

    @NotNull
    private String create_at;

    @NotNull
    private String create_by;

    @NotNull
    private String update_by;

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String email;

    @NotNull
    private String action_id;

    @NotNull
    private String uid;

    @NotNull
    private String mac;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ms_userLoginHistory() {
    }

    public ms_userLoginHistory(Long id) {
        this.id = id;
    }

    @Generated
    public ms_userLoginHistory(String data_sync_status, String data_sync_date, String update_at, String create_at, String create_by, String update_by, Long id, String email, String action_id, String uid, String mac) {
        this.data_sync_status = data_sync_status;
        this.data_sync_date = data_sync_date;
        this.update_at = update_at;
        this.create_at = create_at;
        this.create_by = create_by;
        this.update_by = update_by;
        this.id = id;
        this.email = email;
        this.action_id = action_id;
        this.uid = uid;
        this.mac = mac;
    }

    @NotNull
    public String getData_sync_status() {
        return data_sync_status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setData_sync_status(@NotNull String data_sync_status) {
        this.data_sync_status = data_sync_status;
    }

    @NotNull
    public String getData_sync_date() {
        return data_sync_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setData_sync_date(@NotNull String data_sync_date) {
        this.data_sync_date = data_sync_date;
    }

    @NotNull
    public String getUpdate_at() {
        return update_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdate_at(@NotNull String update_at) {
        this.update_at = update_at;
    }

    @NotNull
    public String getCreate_at() {
        return create_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreate_at(@NotNull String create_at) {
        this.create_at = create_at;
    }

    @NotNull
    public String getCreate_by() {
        return create_by;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreate_by(@NotNull String create_by) {
        this.create_by = create_by;
    }

    @NotNull
    public String getUpdate_by() {
        return update_by;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdate_by(@NotNull String update_by) {
        this.update_by = update_by;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(@NotNull String email) {
        this.email = email;
    }

    @NotNull
    public String getAction_id() {
        return action_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAction_id(@NotNull String action_id) {
        this.action_id = action_id;
    }

    @NotNull
    public String getUid() {
        return uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid(@NotNull String uid) {
        this.uid = uid;
    }

    @NotNull
    public String getMac() {
        return mac;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMac(@NotNull String mac) {
        this.mac = mac;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
